---

- name: gather stuff
  hosts: csr

  tasks:

#  - name: Backup current switch config (ios)
#    ios_config:
#     backup: yes
#    register: backup_ios_location
#    when: ansible_network_os == 'ios'
#  - debug:
#     msg: hello

   - name: modify banner
     ios_banner:
       banner: motd
       text: "{{ motd_message }}"
       state: present
   - debug:
      msg: "{{ motd_message }}"
