---

- name: Gather Nexus Facts
  hosts: switches
  gather_facts: yes

  tasks:
    - nxos_facts:
    - name: Get All Ip Addresses
      debug: var=ansible_net_all_ipv4_addresses
      #debug: var=ansible_net_config 
