---

- name: Gather Nexus Facts
  hosts: nxos
  gather_facts: yes

  tasks:
    - nxos_facts:
    - name: Get All Ip Addresses
      debug: var=ansible_net_all_ipv4_addresses

    - name: Get VLANs
      debug: var=vlan_list
    
